backend/config/routes.rb
FirstWeek::Application.routes.draw do
  resources :tasks

  resources :users

  root :to => 'users#index'
  
  match 'users/get_user/:name' => 'users#get_user'

end

backend/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :user_id
  validates_presence_of :name, :user_id
end

backend/app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  attr_accessible :name
  validates_presence_of :name
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

backend/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
	@user = User.all
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
	@user = User.all
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save!
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        #format.json { render json: @task, status: :created, location: @task }
		format.json { head :no_content}
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
	@user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user.tasks }
    end
  end
  
  # GET /users/get_user/name.json
  def get_user
	@user = User.where("name = ?", params[:name])

    respond_to do |format|
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/tasks_helper.rb
module TasksHelper
end

backend/app/helpers/users_helper.rb
module UsersHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstWeek</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
		<div class="navbar-inner">
			<a id="text_nav_bar" class="brand" href="#"></a>
		</div>
    </div>
    <div class="container-fluid">
    <div class="row-fluid">
    <div class="span2 well">
		<ul class="nav nav-list">
			<li class="nav-header">Users</li>
			<li id="index_users"><%= link_to 'Users', User %></li>
			<li id="new_user"><%= link_to 'New User', new_user_path %></li>
			<li class="nav-header">Tasks</li>
			<li id="index_tasks"><%= link_to 'Tasks', Task %></li>
			<li id="new_task"><%= link_to 'New Task', new_task_path %></li>
		</ul>
    </div>
    <div class="span10 well">
		<%= yield %>
    </div>
    </div>
    </div>
</body>
</html>

backend/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
	<%= f.select :user_id, options_from_collection_for_select(@user, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/tasks/edit.html.erb
<input type="hidden" value="Editing task">

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

backend/app/views/tasks/index.html.erb
<input type="hidden" value="Listing tasks">

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.user.name %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

backend/app/views/tasks/new.html.erb
<input type="hidden" value="New task">

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

backend/app/views/tasks/show.html.erb
<input type="hidden" value="Show task">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>User:</b>
  <%= link_to @task.user.name, @task.user %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

backend/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/users/edit.html.erb
<input type="hidden" value="Editing user">

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

backend/app/views/users/index.html.erb
<input type="hidden" value="Listing users">

<table>
  <tr>
    <th>Name</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

backend/app/views/users/new.html.erb
<input type="hidden" value="New user">

<%= render 'form' %>

<%= link_to 'Back', users_path %>

backend/app/views/users/show.html.erb
<input type="hidden" value="Show user">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Tasks:</b>
</p>

<ul>
  <% @user.tasks.each do |task| %>
    <li><%= link_to task.name, task %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>